name: 'DDeck News'
type: DDeck
description: 'Provides ddeck news configuration'
install:
  - node
  - taxonomy
  - views
  - color_field
  - entity_stretched_link
  - field_formatter_class
  - field_group
  - focal_point
  - helper_class
  - manage_display
  - pathauto
  - scheduler
  - tagify
  - tagify_user_list
config:
  strict: false
